const MAX_WAREHOUSE_QUANTITY = 1000 // kg

const BRONZE_CUSTOMER = 30
const SILVER_CUSTOMER = 50
const GOLD_CUSTOMER = 80
const PLATINUM_CUSTOMER = 100

export {MAX_WAREHOUSE_QUANTITY,BRONZE_CUSTOMER , SILVER_CUSTOMER, GOLD_CUSTOMER, PLATINUM_CUSTOMER  }